### PR TITLE
Partials for Header and Footer

### PR DESCRIPTION
**Pull request by JulienMellon**
Hey Team

I separated the header and footer into partials to keep things dry and so changes can more easily track from view to view

also update the link in the logo / h1 that used to go to index.html but now directs to the root.

Happy Labor Day!

### CODE REVIEW

**Comment by JulienMellon** [comment]
I guess this is pretty much ready to merge, but I didn't want to just push it up to main without making sure it wasn't going to break stuff for everyone else!

**Review by NeffCodes — CHANGES_REQUESTED** [review]
I don't thing you should have the <DOCTYPE> or the html tags. You should have those as layouts and then only have a partial for the navigation or footer stuff

**Comment by JulienMellon** [comment]
OK!  I shortened the header partial; should it also be renamed to something like '_head' ?

**Comment by NeffCodes** [comment]
Up to you. I put "_" in front of a partial to denote that it's "private" but I don't think it matters

**Pull request merged**
